version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  db:
    image: postgres:15
    container_name: db
    ports:
    - "30000:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - parser_postgres_data:/var/lib/postgresql/data/
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser_app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    command: bash -c "alembic upgrade head && python main.py"
    restart: on-failure

volumes:
  parser_postgres_data: