version: "3.2"
services:
  db:
    image: postgres:15
    container_name: db
    ports:
    - "${HOST_POSTGRES_PORT}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - parser_postgres_data:/var/lib/postgresql/data/
    restart: always

  parser_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser_app
    env_file:
      - .env
    depends_on:
      - db
      - translation_app
      - telegram_app
    command: bash -c "alembic upgrade head && python main.py"
    restart: on-failure

  translation_app:
    build:
      context: ./services/
      dockerfile: ./translatiion_service/Dockerfile
    container_name: translation_app
    env_file:
      - .env
    depends_on:
      - db
      - telegram_app
    command: bash -c "python grpc_main.py"
    expose:
      - "${GRPC_TRANSLATION_PORT}"

  telegram_app:
    build:
      context: ./services/
      dockerfile: ./telegram_service/Dockerfile
    container_name: telegram_app
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "python grpc_main.py"
    expose:
      - "${GRPC_TELEGRAM_PORT}"

volumes:
  parser_postgres_data: