"""empty message

Revision ID: 977a72b23dba
Revises: cb5064668a7c
Create Date: 2023-09-27 20:40:53.680300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977a72b23dba'
down_revision: Union[str, None] = 'cb5064668a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('translated_title', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('translated_short_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'translated_short_description')
    op.drop_column('posts', 'translated_title')
    # ### end Alembic commands ###
