"""empty message

Revision ID: cb5064668a7c
Revises: 
Create Date: 2023-09-26 08:07:31.884281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5064668a7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('TRANSTALTION', 'TELEGRAM', 'SENDING_TO_TRANSLATION', 'SENDING_TO_TELEGRAM', name='stepnamechoice'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('errors')
    # ### end Alembic commands ###
